### ISSUE TITLE
Datepicker on modalbox

### ISSUE THREAD

**Issue by lbaguimatang** [freqdec/datePicker#10]
Seems I stumbled upon an error by accident. First I loaded a form on a modalBox(jqueryUI), then cancel/close the form, then load again the form on the modalBox, click the datepicker icon, error encountered.

"TypeError: this.div is undefined"

**Comment by freqdec** [comment]
Hi, any chance of a testcase?

**Comment by freqdec** [comment]
Closing as no testcase given.
