### ISSUE TITLE
You can't select 21th october

### ISSUE THREAD

**Issue by riotera** [freqdec/datePicker#11]
I will try to understand why but if you select 21th october the calendar picks the 20th and overwrite the calendar.

Marco

**Comment by riotera** [comment]
it's due to daylight saving time, in Brazil enter on 21th october, so the time go back to 1 hour (20th october, 23:00)

**Comment by freqdec** [comment]
Hi - you've spotted a bug. I thought that I always set the hour to be 5a.m. to stop daylight savings sillyness like this. I shall have to relook at the code to see where I missed setting the hour!

**Comment by riotera** [comment]
Hi,

I solved the problem in this way, at line 1473:

``` javascript
o.date       = new Date(cellDate.substr(0,4),cellDate.substr(4,2)-1,cellDate.substr(6,2), 12, 0, 0); 
```

I don't know if it is the only place to do it and if it is the best solution.

**Comment by freqdec** [comment]
A long time in coming but I've just updated the code to always set the hour to 5am which should stop daylight savings problems such as this.
