### ISSUE TITLE
Hover indicator is more prominent than selection

### ISSUE THREAD

**Issue by devios1** [freqdec/datePicker#13]
This is bad UI in general as the hovered-over date appears to be the selected date when in fact it is not. You could easily just swap the visual styles of selected vs hover to resolve this.

**Comment by freqdec** [comment]
Hi chaiguy, 

I've updated the CSS to highlight the selected cell in a bolder fashion (bigger & bolder font) which improves things. I'm not particularly convinced that the cursor is more apparent than the selected cell though. I'm open to suggestions - the selected style can be changed by changing only one CSS block within the stylesheet (https://github.com/freqdec/datePicker/blob/master/css/datepicker.css#L670) so feel free to give it a whirl. Design never was my strong point.

**Comment by devios1** [comment]
Hi freqdec, I ended up tweaking the css myself as you suggested, so this is not as big an issue to me anymore, however I do feel the selected style should definitely be more prominent than the hover style. I actually just swapped them like I suggested and find it looks quite good. I decreased the contrast of the hover (previously selected) border so there's just a hint of change when you hover a cell, which, in my opinion is all you need. I think the colored-in cell makes a much better selected date style than hover style, imo. I don't find your design skills lacking at all, just your decision of which styles to use for what. ;)
