### ISSUE TITLE
Status bar shows date of hover indicator, not selected date

### ISSUE THREAD

**Issue by devios1** [freqdec/datePicker#15]
The status bar shows the date the mouse was last hovered over, not the chosen date, even after the mouse has moved off the control. This makes the status bar effectively useless if one does not want to greatly confuse users.

**Comment by freqdec** [comment]
I've updated the script to use the selected date (if any) as a message or, if no selected date, the "Select a date" message (or appropriate translation).

**Comment by devios1** [comment]
Excellent, thanks for heeding my suggestions! Best date picker I've used.
