### ISSUE TITLE
add possibility to select multiple dates

### ISSUE THREAD

**Issue by arnederuwe** [freqdec/datePicker#16]
Hi, 

Is it possible to select multiple dates?
So instead of a SelectedDate property you would have a list of selected dates.
Would this be hard to implement? If not, can you point me in a direction?

Thanks!

Arne

**Comment by freqdec** [comment]
Hi,

A lot of work to implement actually and many, many unanswered questions e.g. parsing the input value if multiple dates are stored within, setting the input value to store multiple dates etc. Not really feasable with the current script I think.

Regards,
Brian
