### ISSUE TITLE
Set the date where the calendar defaults to / Where is the documentation for Datepicker?

### ISSUE THREAD

**Issue by eaglejs** [freqdec/datePicker#19]
I was curious where the documentation is for Datepicker.js. I saw that you have a blog link at the bottom pointing to "http://www.frequency-decoder.com/" however it appears to be down. I am trying to set the date of the calendar to January 1, 2014. I don't want it to load on today's date.

**Comment by freqdec** [comment]
Yeah, my website took a nosedive! I've moved the docs to github http://freqdec.github.io/datePicker/ and http://freqdec.github.io/datePicker/demo/

I think you may be looking for the cursorDate parameter: http://freqdec.github.io/datePicker/#setting-the-default-cursor-date
