### ISSUE TITLE
Header is crowded in Safari

### ISSUE THREAD

**Issue by gavmor** [freqdec/datePicker#22]
The header is displaying with 0 height and width in Safari.  You can see this pretty clearly from this [Fiddle](http://jsfiddle.net/tqQUx/). 
### Safari:

![screen shot 2013-08-15 at 10 33 51 am](https://f.cloud.github.com/assets/606529/970139/e08222a6-05d0-11e3-9054-eeb4efb64b0c.png)
### Chrome:

![screen shot 2013-08-15 at 10 32 52 am](https://f.cloud.github.com/assets/606529/970135/c3f9c436-05d0-11e3-9fda-87fcc02762cd.png)

**Comment by freqdec** [comment]
Hi, I can't appear to reproduce this in Safari 5.1.7 (Windows). I shall try to grab a Mac and check it again later today.
