### ISSUE TITLE
TimePicker

### ISSUE THREAD

**Issue by ursusArctos19** [freqdec/datePicker#28]
Hello,

Can you add a option to create a timePicker (just two input element under the table) with the datePicker ?

Thank you.

**Comment by freqdec** [comment]
Hi, actually I won't be doing this as it will add huge amounts of code for something that can easily be handled in a quick create callback function. Date parsing gets way more complicated, the U.I. code would bloat even further and no two people appear to want the same things displayed in the select lists (do I display 10p.m. or 22 etc) or the same values sent to the server.

Many apologies - it sounds harsh I know - but I really just want to limit the script to date and not datetime values.
