### ISSUE TITLE
Top value problem in Chrome

### ISSUE THREAD

**Issue by orphen92** [freqdec/datePicker#32]
Hi man,
thanks for this datepicker.
I want use it but i see in you demo.
http://freqdec.github.io/datePicker/demo/

the value of top in chrome are not good.
Its flagrant in demo 8.
it really looks like the datepicker does not appear he is just too high in the page

can you help me?

thanks

**Comment by johnmarlow007** [comment]
Hello.
I have the same problem. 

The datepicker is great but it just has this issue in Chrome. 

I contacted them also to see if they have a fix for their browser. 

Also, in IE9 the passed dates are still selectable. 

Can anything be done about those issues ?

**Comment by orphen92** [comment]
Have you had a response from the developer?

**Comment by jcunningdev** [comment]
I'll take a look at it and see if I can't fix it this weekend. I'm not the developer but I also depend on this library.

**Comment by johnmarlow007** [comment]
I am the developer of the website. 
I found a solution by using another datepicker, which is the one from
jquery ui and as I saw that one worked fine on chrome. 
Thank you very much for your effort.

 

---

Best regards, 
Dragos Adrian

www.ArtitMedia.eu
www.RegionAd.co.uk

www.BuySell247.co.uk
www.Horse-Bound.co.uk

On Tuesday, February 18, 2014 9:39 AM, jcunningdev notifications@github.com wrote:

I'll take a look at it and see if I can't fix it this weekend. I'm not the developer but I also depend on this library.

**Comment by orphen92** [comment]
Thanks you,
but use another datepicker is not the solution for this datepicker.
Freqdec / datePicker is realy good for accessibility.

nobody else has a better solution ?

**Comment by johnmarlow007** [comment]
I know, but I had the client on my back and I had to find a quick solution. 
Plus, I am a freelance web developer, earning very little money from it so I do not have the time to go through all the debugging and fixing in a more detailed way.
Thank you for your support. 
Anyway, that freq datepicker was faulty in IE too, it did not hide the passed dates. 
The jquery one fixed both, so...  

---

Best regards, 
Dragos Adrian

www.ArtitMedia.eu
www.RegionAd.co.uk

www.BuySell247.co.uk
www.Horse-Bound.co.uk
www.Opsido.co.uk

On Friday, February 21, 2014 9:31 AM, orphen92 notifications@github.com wrote:

Thanks you,
but use another datepicker is not the solution for this datepicker.
Freqdec / datePicker is realy good for accessibility.
nobody else has a better solution ?

**Comment by freqdec** [comment]
Hi Guys,

The real developer here. Many, many apologies for taking so long to reply.

It looks like Chrome 33.0.1750.117 fixes the problem as I can no longer reproduce this bug. 

Also, please forget the trolling from the ass-hat above "artitmedia".

Leaving issue open until I can test on a few other machines.

**Comment by orphen92** [comment]
I'm confirm,

Its ok in Chrome now! great news!! thanks Freqdec.

**Comment by johnmarlow007** [comment]
:) Its good its ok now, when I dont use it anymore
Anyway, great job people !!! 

---

Best regards, 
Dragos Adrian
07564649772
www.ArtitMedia.eu
www.RegionAd.co.uk

www.BuySell247.co.uk
www.Horse-Bound.co.uk
www.Opsido.co.uk

On Wednesday, February 26, 2014 9:29 AM, orphen92 notifications@github.com wrote:

I'm confirm,
Its ok in Chrome now! great news!! thanks Freqdec.
