### ISSUE TITLE
Timing of dateset callback

### ISSUE THREAD

**Issue by phillipkoebbe** [freqdec/datePicker#4]
This isn't so much an issue as an inquiry. I searched for an email address for you but didn't find one. Either I didn't search hard/long enough (highly likely), or you don't want to have emails sent directly to you (quite possible, which is fine...just acknowledging the possibilities).

I've noticed that when my dateset callback is called, the associated form element has not yet had its value updated. I looked at the code, and I see that you are calling the dateset callback right before returnFormattedDate, which is where the value gets updated. I'm wondering if it would make more sense to call the dateset callback after updating the value in returnFormattedDate.

I do see, however, there is one time you call the dateset callback without calling returnFormattedDate (in changeHandler) and one time you call returnFormattedDate without calling the dateset callback (in setDateFromInput). Will you shed some light on the reasoning?

Beyond that, is it possible for datePicker to fire the associated form element's change event after updating it? That would really solve my problem and possibly be the right behavior.

**Comment by phillipkoebbe** [comment]
After looking at it further, I see why it's difficult to call an onchange event. It occurred to me that just knowing when the form element's value has been updated would be sufficient, so I added a 'datereturned' call back at the end of returnFormattedDate. It's very, very simple:

https://github.com/phillipkoebbe/datePicker/commit/72ed7b51a6fc6b9e6ef9dfe87a47cf7da704aa5a

I didn't make a pull request because I wasn't sure what implications this would have elsewhere. I added the !noFocus condition because I noticed that the callback was called during the initial association of the datePicker with the form element and I didn't care about it then. In my (admittedly) quick tests, this looks like it works correctly.

[Not sure why the 'if' statement didn't get indented ... ]

**Comment by freqdec** [comment]
Hi Phillip,

All callback functions get passed the input value (or, more precisely, the value the input will have after callback completes) so you shouldn't need to check the input.value. 

I like the datereturned callback idea though so shall merge it in later tonight when I'm at home.

Thanks for taking the time to post the issue.

**Comment by phillipkoebbe** [comment]
Hey Brian,

I'm glad you like the datereturned idea. Do you want me to create a pull request?

I did discover that the date was passed to the callback function, but in my case, that function was already being used as an onchange event handler. At the time the function is invoked, it expects the value of the input to be set. I thought about checking the argument passed in and if it was an event just doing what it usually does but if it was a date use that value. In the end I decided that I didn't want to have that decision in my code since it is used by more than just date-related input fields. I thought it would be too tightly coupled. That's when I started looking at your code and thinking that if I just knew when the datePicker was done, that would solve my problem.

But hey, since you like the datereturned idea, it's all moot now!

Thanks for the awesome tool!

**Comment by freqdec** [comment]
Yeah - hit me with a pull request. It's always nice to have people helping with the project!

**Comment by phillipkoebbe** [comment]
Commit 3efbbc2d4c51aff60a2765a412da1fb88acb1e8e merged in the datereturned callback. Issue closed.
