### ISSUE TITLE
After Popup is hidden it Stays Active in the UI on IE11

### ISSUE THREAD

**Issue by DVmitchell** [freqdec/datePicker#51]
On IE11, after datePicker popup is shown and then hidden (by clicking elsewhere), the hidden popup is still active even though it is invisible.  It still controls the cursor and still flashes messages as the cursor moves over (invisible) dates.  Controls that are "under" the hidden datePicker are inaccessible.
The problem occurs on Internet Explorer 11.  I have tried it on Firefox, Chrome and Safari and they do not exhibit the problem.

Windows 7 64bit
IE 11.0.9600.17420

**Comment by freqdec** [comment]
Fixed in latest commit.

**Comment by DVmitchell** [comment]
Thank you for the prompt reply.  This is a nice DatePicker!

**Comment by dimkalinux** [comment]
Same error reproduces on Mac On Safari Version 5.1.10 (6534.59.10).

**Comment by dimkalinux** [comment]
Same error reproduces on Mac On Safari Version 5.1.10 (6534.59.10).

/*! DatePicker v6.3.6 MIT/GPL2 @freqdec */
