### ISSUE TITLE
disable dates on select

### ISSUE THREAD

**Issue by niels-heinemann** [freqdec/datePicker#7]
Hi there,

wonderful work!

I wonder if there's a way to set disabled or enabled days of a second datepicker on firing an onselect event of a first datepicker. I'm coding sort of a booking form with datepickers for start and end of the booking request. Already booked dates are disabled by using setDisabledDates. The idea is to set all dates of the end date picker to disabled at first page load and enable dates dependend on the selection in the first datepicker. Otherwise users can select end dates past to the next booked out period...

Any idea?

thx in advance // nielo

**Comment by freqdec** [comment]
The "soon to be uploaded" new version has a quick booking demo that may interest you:

http://www.frequency-decoder.com/datePicker/booking/

Shall push latest code tonight.

**Comment by niels-heinemann** [comment]
Oh nice. Thx a load!
